source 'https://rubygems.org'
gem 'html-proofer'
gem 'jekyll', '~> 2.5.3'
gem 'jekyll-redirect-from', '~> 0.8.0'
gem 'RedCloth', '~> 4.2.9'
gem 'i18n', '~> 0.7.0'
gem 'json', '~> 1.8.2'
gem 'minitest', '~> 5.6.1'
gem 'tzinfo', '~> 1.2.2'
gem 'activesupport', '~> 4.2.1'
gem 'pry'
gem 'rouge'
